### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KadTheHunter** [tim03we/GunGame#1]
Is this similar to a plugin i saw recently, in the sense that it works on a server-wide scale (and therefore 1 server technically equals 1 arena)? Or can i load it on a server with other Minigames?

**Comment by tim03we** [comment]
This MiniGame is only suitable for single servers, if you want it to run on multiple servers, you have to rewrite it yourself.

**Comment by tim03we** [comment]
Let's see, maybe I'll add it when the demand is high.

**Comment by KadTheHunter** [comment]
To clarify (as looking back, my question was badly worded), i have a server thats Plots + Adventure Maps, and im curious if GunGame would work with that (and therefore, we are able to Start/Stop/Join/Leave matches relatively at will).

**Comment by tim03we** [comment]
In my experience, MiniGames belong on single servers to not affect other games or performance. GunGame is currently only intended for single servers and not for multi-functional servers where everything runs on it. Have patience, I'm already on it.

**Comment by Wertzui123** [comment]
This is difficult, but it would be cool

**Comment by tim03we** [comment]
It's not difficult. Theoretically it would only have to check the world and update the sign every time.

**Comment by Wertzui123** [comment]
Hm, you already have the most of the difficult part, but for me it would be difficult anyway :joy:

**Comment by tim03we** [comment]
Everybody starts small, but GunGame is not really something heavy.

**Comment by Wertzui123** [comment]
Okey :thinking:

**Comment by tim03we** [comment]
I just have to see if I allow single or multiple worlds. But think several, I don't know yet.

**Comment by Wertzui123** [comment]
Ok

**Comment by KadTheHunter** [comment]
Thx for the answer 😄
I'll look forward to the updates

**Comment by tim03we** [comment]
Have a nice day.
