### ISSUE TITLE
Settings and level always renamed

### ISSUE THREAD

**Issue by benda95280** [tim03we/GunGame#3]
Hello,

It seems Settings and Level are always erased for me :(
No matter if i change something inside or not.

Thanks

**Comment by tim03we** [comment]
I'll take a closer look.

**Comment by Wertzui123** [comment]
The settings shouldn't be renamed, but the level should. @tim03we forgot about a part of the config updater, and now it won't work, until you change the config version to 1.0.0, but then the settings wil be renamed. I just made a pr to fix this. 

PS: I think I found the error for the settings.yml too!

**Comment by tim03we** [comment]
I've found the error for a long time, I ask you to delete the fork again. I will upload the update now.

**Comment by tim03we** [comment]
@benda95280 problem fixed now.
