### ISSUE TITLE
[Feature Request] Option to allow ops to edit map

### ISSUE THREAD

**Issue by marchershey** [tim03we/GunGame#5]
So I wish we could have a feature where if we need to make a change to the map, we could do something like `/gungame edit` and it would allow ops (or whatever group) to break/edit the maps. 

Thanks

**Comment by RagnarTeam** [comment]
Is this plugin work without problems? cuz i want to update it to pm4

**Comment by RagnarTeam** [comment]
> 



> Is this plugin work without problems? cuz i want to update it to pm4

**Comment by marchershey** [comment]
> Is this plugin work without problems? cuz i want to update it to pm4

You decided to ask this question on an issue created over 2.5 years ago?
